/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordsRouteImport } from './routes/words'
import { Route as WhackRouteImport } from './routes/whack'
import { Route as SwitchRouteImport } from './routes/switch'
import { Route as StroopRouteImport } from './routes/stroop'
import { Route as StopgoRouteImport } from './routes/stopgo'
import { Route as SpotRouteImport } from './routes/spot'
import { Route as SortRouteImport } from './routes/sort'
import { Route as SimonRouteImport } from './routes/simon'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RhythmRouteImport } from './routes/rhythm'
import { Route as ReactionRouteImport } from './routes/reaction'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as PlandoRouteImport } from './routes/plando'
import { Route as OddoneRouteImport } from './routes/oddone'
import { Route as NbackRouteImport } from './routes/nback'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MathRouteImport } from './routes/math'
import { Route as LearnplayRouteImport } from './routes/learnplay'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as HoldRouteImport } from './routes/hold'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as FlankerRouteImport } from './routes/flanker'
import { Route as BreatheRouteImport } from './routes/breathe'
import { Route as IndexRouteImport } from './routes/index'

const WordsRoute = WordsRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => rootRouteImport,
} as any)
const WhackRoute = WhackRouteImport.update({
  id: '/whack',
  path: '/whack',
  getParentRoute: () => rootRouteImport,
} as any)
const SwitchRoute = SwitchRouteImport.update({
  id: '/switch',
  path: '/switch',
  getParentRoute: () => rootRouteImport,
} as any)
const StroopRoute = StroopRouteImport.update({
  id: '/stroop',
  path: '/stroop',
  getParentRoute: () => rootRouteImport,
} as any)
const StopgoRoute = StopgoRouteImport.update({
  id: '/stopgo',
  path: '/stopgo',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotRoute = SpotRouteImport.update({
  id: '/spot',
  path: '/spot',
  getParentRoute: () => rootRouteImport,
} as any)
const SortRoute = SortRouteImport.update({
  id: '/sort',
  path: '/sort',
  getParentRoute: () => rootRouteImport,
} as any)
const SimonRoute = SimonRouteImport.update({
  id: '/simon',
  path: '/simon',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RhythmRoute = RhythmRouteImport.update({
  id: '/rhythm',
  path: '/rhythm',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactionRoute = ReactionRouteImport.update({
  id: '/reaction',
  path: '/reaction',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const PlandoRoute = PlandoRouteImport.update({
  id: '/plando',
  path: '/plando',
  getParentRoute: () => rootRouteImport,
} as any)
const OddoneRoute = OddoneRouteImport.update({
  id: '/oddone',
  path: '/oddone',
  getParentRoute: () => rootRouteImport,
} as any)
const NbackRoute = NbackRouteImport.update({
  id: '/nback',
  path: '/nback',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MathRoute = MathRouteImport.update({
  id: '/math',
  path: '/math',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnplayRoute = LearnplayRouteImport.update({
  id: '/learnplay',
  path: '/learnplay',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldRoute = HoldRouteImport.update({
  id: '/hold',
  path: '/hold',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const FlankerRoute = FlankerRouteImport.update({
  id: '/flanker',
  path: '/flanker',
  getParentRoute: () => rootRouteImport,
} as any)
const BreatheRoute = BreatheRouteImport.update({
  id: '/breathe',
  path: '/breathe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/breathe': typeof BreatheRoute
  '/flanker': typeof FlankerRoute
  '/focus': typeof FocusRoute
  '/games': typeof GamesRoute
  '/guide': typeof GuideRoute
  '/hold': typeof HoldRoute
  '/learn': typeof LearnRoute
  '/learnplay': typeof LearnplayRoute
  '/math': typeof MathRoute
  '/memory': typeof MemoryRoute
  '/nback': typeof NbackRoute
  '/oddone': typeof OddoneRoute
  '/plando': typeof PlandoRoute
  '/quests': typeof QuestsRoute
  '/reaction': typeof ReactionRoute
  '/rhythm': typeof RhythmRoute
  '/settings': typeof SettingsRoute
  '/simon': typeof SimonRoute
  '/sort': typeof SortRoute
  '/spot': typeof SpotRoute
  '/stopgo': typeof StopgoRoute
  '/stroop': typeof StroopRoute
  '/switch': typeof SwitchRoute
  '/whack': typeof WhackRoute
  '/words': typeof WordsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/breathe': typeof BreatheRoute
  '/flanker': typeof FlankerRoute
  '/focus': typeof FocusRoute
  '/games': typeof GamesRoute
  '/guide': typeof GuideRoute
  '/hold': typeof HoldRoute
  '/learn': typeof LearnRoute
  '/learnplay': typeof LearnplayRoute
  '/math': typeof MathRoute
  '/memory': typeof MemoryRoute
  '/nback': typeof NbackRoute
  '/oddone': typeof OddoneRoute
  '/plando': typeof PlandoRoute
  '/quests': typeof QuestsRoute
  '/reaction': typeof ReactionRoute
  '/rhythm': typeof RhythmRoute
  '/settings': typeof SettingsRoute
  '/simon': typeof SimonRoute
  '/sort': typeof SortRoute
  '/spot': typeof SpotRoute
  '/stopgo': typeof StopgoRoute
  '/stroop': typeof StroopRoute
  '/switch': typeof SwitchRoute
  '/whack': typeof WhackRoute
  '/words': typeof WordsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/breathe': typeof BreatheRoute
  '/flanker': typeof FlankerRoute
  '/focus': typeof FocusRoute
  '/games': typeof GamesRoute
  '/guide': typeof GuideRoute
  '/hold': typeof HoldRoute
  '/learn': typeof LearnRoute
  '/learnplay': typeof LearnplayRoute
  '/math': typeof MathRoute
  '/memory': typeof MemoryRoute
  '/nback': typeof NbackRoute
  '/oddone': typeof OddoneRoute
  '/plando': typeof PlandoRoute
  '/quests': typeof QuestsRoute
  '/reaction': typeof ReactionRoute
  '/rhythm': typeof RhythmRoute
  '/settings': typeof SettingsRoute
  '/simon': typeof SimonRoute
  '/sort': typeof SortRoute
  '/spot': typeof SpotRoute
  '/stopgo': typeof StopgoRoute
  '/stroop': typeof StroopRoute
  '/switch': typeof SwitchRoute
  '/whack': typeof WhackRoute
  '/words': typeof WordsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/breathe'
    | '/flanker'
    | '/focus'
    | '/games'
    | '/guide'
    | '/hold'
    | '/learn'
    | '/learnplay'
    | '/math'
    | '/memory'
    | '/nback'
    | '/oddone'
    | '/plando'
    | '/quests'
    | '/reaction'
    | '/rhythm'
    | '/settings'
    | '/simon'
    | '/sort'
    | '/spot'
    | '/stopgo'
    | '/stroop'
    | '/switch'
    | '/whack'
    | '/words'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/breathe'
    | '/flanker'
    | '/focus'
    | '/games'
    | '/guide'
    | '/hold'
    | '/learn'
    | '/learnplay'
    | '/math'
    | '/memory'
    | '/nback'
    | '/oddone'
    | '/plando'
    | '/quests'
    | '/reaction'
    | '/rhythm'
    | '/settings'
    | '/simon'
    | '/sort'
    | '/spot'
    | '/stopgo'
    | '/stroop'
    | '/switch'
    | '/whack'
    | '/words'
  id:
    | '__root__'
    | '/'
    | '/breathe'
    | '/flanker'
    | '/focus'
    | '/games'
    | '/guide'
    | '/hold'
    | '/learn'
    | '/learnplay'
    | '/math'
    | '/memory'
    | '/nback'
    | '/oddone'
    | '/plando'
    | '/quests'
    | '/reaction'
    | '/rhythm'
    | '/settings'
    | '/simon'
    | '/sort'
    | '/spot'
    | '/stopgo'
    | '/stroop'
    | '/switch'
    | '/whack'
    | '/words'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BreatheRoute: typeof BreatheRoute
  FlankerRoute: typeof FlankerRoute
  FocusRoute: typeof FocusRoute
  GamesRoute: typeof GamesRoute
  GuideRoute: typeof GuideRoute
  HoldRoute: typeof HoldRoute
  LearnRoute: typeof LearnRoute
  LearnplayRoute: typeof LearnplayRoute
  MathRoute: typeof MathRoute
  MemoryRoute: typeof MemoryRoute
  NbackRoute: typeof NbackRoute
  OddoneRoute: typeof OddoneRoute
  PlandoRoute: typeof PlandoRoute
  QuestsRoute: typeof QuestsRoute
  ReactionRoute: typeof ReactionRoute
  RhythmRoute: typeof RhythmRoute
  SettingsRoute: typeof SettingsRoute
  SimonRoute: typeof SimonRoute
  SortRoute: typeof SortRoute
  SpotRoute: typeof SpotRoute
  StopgoRoute: typeof StopgoRoute
  StroopRoute: typeof StroopRoute
  SwitchRoute: typeof SwitchRoute
  WhackRoute: typeof WhackRoute
  WordsRoute: typeof WordsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/words': {
      id: '/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof WordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whack': {
      id: '/whack'
      path: '/whack'
      fullPath: '/whack'
      preLoaderRoute: typeof WhackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/switch': {
      id: '/switch'
      path: '/switch'
      fullPath: '/switch'
      preLoaderRoute: typeof SwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stroop': {
      id: '/stroop'
      path: '/stroop'
      fullPath: '/stroop'
      preLoaderRoute: typeof StroopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stopgo': {
      id: '/stopgo'
      path: '/stopgo'
      fullPath: '/stopgo'
      preLoaderRoute: typeof StopgoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spot': {
      id: '/spot'
      path: '/spot'
      fullPath: '/spot'
      preLoaderRoute: typeof SpotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sort': {
      id: '/sort'
      path: '/sort'
      fullPath: '/sort'
      preLoaderRoute: typeof SortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simon': {
      id: '/simon'
      path: '/simon'
      fullPath: '/simon'
      preLoaderRoute: typeof SimonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rhythm': {
      id: '/rhythm'
      path: '/rhythm'
      fullPath: '/rhythm'
      preLoaderRoute: typeof RhythmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reaction': {
      id: '/reaction'
      path: '/reaction'
      fullPath: '/reaction'
      preLoaderRoute: typeof ReactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plando': {
      id: '/plando'
      path: '/plando'
      fullPath: '/plando'
      preLoaderRoute: typeof PlandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oddone': {
      id: '/oddone'
      path: '/oddone'
      fullPath: '/oddone'
      preLoaderRoute: typeof OddoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nback': {
      id: '/nback'
      path: '/nback'
      fullPath: '/nback'
      preLoaderRoute: typeof NbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math': {
      id: '/math'
      path: '/math'
      fullPath: '/math'
      preLoaderRoute: typeof MathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learnplay': {
      id: '/learnplay'
      path: '/learnplay'
      fullPath: '/learnplay'
      preLoaderRoute: typeof LearnplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hold': {
      id: '/hold'
      path: '/hold'
      fullPath: '/hold'
      preLoaderRoute: typeof HoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flanker': {
      id: '/flanker'
      path: '/flanker'
      fullPath: '/flanker'
      preLoaderRoute: typeof FlankerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breathe': {
      id: '/breathe'
      path: '/breathe'
      fullPath: '/breathe'
      preLoaderRoute: typeof BreatheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BreatheRoute: BreatheRoute,
  FlankerRoute: FlankerRoute,
  FocusRoute: FocusRoute,
  GamesRoute: GamesRoute,
  GuideRoute: GuideRoute,
  HoldRoute: HoldRoute,
  LearnRoute: LearnRoute,
  LearnplayRoute: LearnplayRoute,
  MathRoute: MathRoute,
  MemoryRoute: MemoryRoute,
  NbackRoute: NbackRoute,
  OddoneRoute: OddoneRoute,
  PlandoRoute: PlandoRoute,
  QuestsRoute: QuestsRoute,
  ReactionRoute: ReactionRoute,
  RhythmRoute: RhythmRoute,
  SettingsRoute: SettingsRoute,
  SimonRoute: SimonRoute,
  SortRoute: SortRoute,
  SpotRoute: SpotRoute,
  StopgoRoute: StopgoRoute,
  StroopRoute: StroopRoute,
  SwitchRoute: SwitchRoute,
  WhackRoute: WhackRoute,
  WordsRoute: WordsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
