/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhackRouteImport } from './routes/whack'
import { Route as StopgoRouteImport } from './routes/stopgo'
import { Route as SimonRouteImport } from './routes/simon'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReactionRouteImport } from './routes/reaction'
import { Route as OddoneRouteImport } from './routes/oddone'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as BreatheRouteImport } from './routes/breathe'
import { Route as IndexRouteImport } from './routes/index'

const WhackRoute = WhackRouteImport.update({
  id: '/whack',
  path: '/whack',
  getParentRoute: () => rootRouteImport,
} as any)
const StopgoRoute = StopgoRouteImport.update({
  id: '/stopgo',
  path: '/stopgo',
  getParentRoute: () => rootRouteImport,
} as any)
const SimonRoute = SimonRouteImport.update({
  id: '/simon',
  path: '/simon',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactionRoute = ReactionRouteImport.update({
  id: '/reaction',
  path: '/reaction',
  getParentRoute: () => rootRouteImport,
} as any)
const OddoneRoute = OddoneRouteImport.update({
  id: '/oddone',
  path: '/oddone',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const BreatheRoute = BreatheRouteImport.update({
  id: '/breathe',
  path: '/breathe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/breathe': typeof BreatheRoute
  '/focus': typeof FocusRoute
  '/games': typeof GamesRoute
  '/learn': typeof LearnRoute
  '/memory': typeof MemoryRoute
  '/oddone': typeof OddoneRoute
  '/reaction': typeof ReactionRoute
  '/settings': typeof SettingsRoute
  '/simon': typeof SimonRoute
  '/stopgo': typeof StopgoRoute
  '/whack': typeof WhackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/breathe': typeof BreatheRoute
  '/focus': typeof FocusRoute
  '/games': typeof GamesRoute
  '/learn': typeof LearnRoute
  '/memory': typeof MemoryRoute
  '/oddone': typeof OddoneRoute
  '/reaction': typeof ReactionRoute
  '/settings': typeof SettingsRoute
  '/simon': typeof SimonRoute
  '/stopgo': typeof StopgoRoute
  '/whack': typeof WhackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/breathe': typeof BreatheRoute
  '/focus': typeof FocusRoute
  '/games': typeof GamesRoute
  '/learn': typeof LearnRoute
  '/memory': typeof MemoryRoute
  '/oddone': typeof OddoneRoute
  '/reaction': typeof ReactionRoute
  '/settings': typeof SettingsRoute
  '/simon': typeof SimonRoute
  '/stopgo': typeof StopgoRoute
  '/whack': typeof WhackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/breathe'
    | '/focus'
    | '/games'
    | '/learn'
    | '/memory'
    | '/oddone'
    | '/reaction'
    | '/settings'
    | '/simon'
    | '/stopgo'
    | '/whack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/breathe'
    | '/focus'
    | '/games'
    | '/learn'
    | '/memory'
    | '/oddone'
    | '/reaction'
    | '/settings'
    | '/simon'
    | '/stopgo'
    | '/whack'
  id:
    | '__root__'
    | '/'
    | '/breathe'
    | '/focus'
    | '/games'
    | '/learn'
    | '/memory'
    | '/oddone'
    | '/reaction'
    | '/settings'
    | '/simon'
    | '/stopgo'
    | '/whack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BreatheRoute: typeof BreatheRoute
  FocusRoute: typeof FocusRoute
  GamesRoute: typeof GamesRoute
  LearnRoute: typeof LearnRoute
  MemoryRoute: typeof MemoryRoute
  OddoneRoute: typeof OddoneRoute
  ReactionRoute: typeof ReactionRoute
  SettingsRoute: typeof SettingsRoute
  SimonRoute: typeof SimonRoute
  StopgoRoute: typeof StopgoRoute
  WhackRoute: typeof WhackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whack': {
      id: '/whack'
      path: '/whack'
      fullPath: '/whack'
      preLoaderRoute: typeof WhackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stopgo': {
      id: '/stopgo'
      path: '/stopgo'
      fullPath: '/stopgo'
      preLoaderRoute: typeof StopgoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simon': {
      id: '/simon'
      path: '/simon'
      fullPath: '/simon'
      preLoaderRoute: typeof SimonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reaction': {
      id: '/reaction'
      path: '/reaction'
      fullPath: '/reaction'
      preLoaderRoute: typeof ReactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oddone': {
      id: '/oddone'
      path: '/oddone'
      fullPath: '/oddone'
      preLoaderRoute: typeof OddoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breathe': {
      id: '/breathe'
      path: '/breathe'
      fullPath: '/breathe'
      preLoaderRoute: typeof BreatheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BreatheRoute: BreatheRoute,
  FocusRoute: FocusRoute,
  GamesRoute: GamesRoute,
  LearnRoute: LearnRoute,
  MemoryRoute: MemoryRoute,
  OddoneRoute: OddoneRoute,
  ReactionRoute: ReactionRoute,
  SettingsRoute: SettingsRoute,
  SimonRoute: SimonRoute,
  StopgoRoute: StopgoRoute,
  WhackRoute: WhackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
